name: cicd-pipeline
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ci:
    env:
      GO111MODULE: on
    runs-on: ubuntu-latest        
    steps:
    - name: setup-go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: checkout src
      run: |
        mkdir /home/runner/go/src
        cd /home/runner/go/src
        mkdir k8s.io
        cd k8s.io
        git clone https://github.com/kubernetes/kube-openapi.git
    - name: build
      run: |
        cd /home/runner/go/src/k8s.io/kube-openapi
        echo "Running go mod"
        echo "---------------" &&
        go mod tidy
        git diff --exit-code
        echo "Running go build"
        echo "--------------------"
        go build -v ./cmd/... ./pkg/...
        touch foobar
    - name: test cmd and pkg
      run: |
        cd /home/runner/go/src/k8s.io/kube-openapi
        pwd && ls -a
        GOPATH=/home/runner/go go test ./cmd/... ./pkg/...
    - name: test integration
      run: |
        cd /home/runner/go/src/k8s.io/kube-openapi
        pwd && ls -a
        GOPATH=/home/runner/go go test ./test/...
