name: CICD-Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  ci:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:
      - uses: actions/checkout@v2

      - name: Setup-Go
        uses: actions/setup-go@v2

      - name: go mod
        run: go mod tidy && git diff --exit-code

      - name: go build
        run: go build ./cmd/... ./pkg/...

      - name: Get env details for test
        run: echo "Test will run under below environment" && echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" && date && env && pwd && ls -ltha && go env && echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

      - name: go test
        run: go test ./cmd/... ./pkg/... ./test/...
